### ISSUE TITLE
00 Connecting to a Blockchain Network bug on the last editor

### ISSUE THREAD

**Issue by andrewmamus** [kay-is/web3-from-zero#2]
![Screenshot from 2022-02-17 16-48-14](https://user-images.githubusercontent.com/42706394/154518260-ea80eed9-626d-471c-8f77-2a409683bb6e.png)

There is a syntax error.
**To reproduce the error**
use the editor to write the instructed code and the bug will show  up
`const block = await provider.getBlock()
`
`print(block)`

**Comment by kay-is** [comment]
What browser version are you using?

**Comment by andrewmamus** [comment]
I used firefox let me try it with chrome browser and edge

**Comment by kay-is** [comment]
I'll close this for now.

If this is still an issue, I'll reopen.
